import type { PortfolioAsset } from '../catalog/domain/types';
import type { QualitySnapshot } from '../catalog/quality/qualitySnapshotStore';
import type { SubmissionRecord } from '../catalog/submission/submissionRecord';
import { MARKETPLACE_LIST } from '../metadata/marketplaceProfiles';
import {
  READINESS_CATEGORY_WEIGHTS,
  DEFAULT_READINESS_THRESHOLD,
  type ReadinessCheck,
  type ReadinessCheckId,
  type ReadinessCategory,
  type CommercialReadinessReport,
  type CommercialReadinessBand,
} from './domain/types';

// Build 031A, Phase 1 — Commercial Readiness Engine. Every check below
// reads only real, already-persisted data (the same `PortfolioAsset`/
// `QualitySnapshot`/`SubmissionRecord` records every other catalog module
// already produces) — this engine adds no new scoring model of its own for
// quality/SEO/duplicate detection, it only asks each existing subsystem
// "are you satisfied for this asset?" and combines the honest PASS/
// WARNING/FAIL answers into one weighted 0-100 score, matching the spec's
// explicit "No fabricated values" requirement.

const CHECK_CATEGORY: Record<ReadinessCheckId, ReadinessCategory> = {
  generatorCompleted: 'artwork',
  svgExists: 'artwork',
  epsExists: 'artwork',
  previewExists: 'artwork',
  metadataExists: 'metadata',
  seoExists: 'seo',
  collectionAssignment: 'collection',
  marketplacePackage: 'marketplacePackage',
  qaPassed: 'qa',
  commercialScoreAvailable: 'qa',
  beautyScoreAvailable: 'qa',
  duplicateCheckComplete: 'traceability',
  repairHistoryComplete: 'traceability',
  exportValidationComplete: 'export',
};

/** Blocking a package on these specific fundamentals (rather than only on
 * the aggregate score) means a technically-high score built from many
 * WARNINGs can never disguise a genuinely missing artwork/collection/QA
 * fact as "READY." */
const FUNDAMENTAL_BLOCKERS: ReadinessCheckId[] = ['generatorCompleted', 'svgExists', 'collectionAssignment', 'qaPassed'];

export interface ReadinessEngineInput {
  asset: PortfolioAsset;
  qualitySnapshot: QualitySnapshot | null;
  /** Submissions already filtered to this asset (by `patternId === asset.assetId`,
   * the same convention `submissionPackageBuilder.ts` uses). */
  submissionsForAsset: SubmissionRecord[];
  /** The rest of the portfolio (excluding this asset) — used only for the
   * duplicate-productionAssetId check. */
  siblingAssets: PortfolioAsset[];
  now?: number;
}

function checkGeneratorCompleted(asset: PortfolioAsset): ReadinessCheck {
  const status = asset.generatorVersion !== null ? 'PASS' : 'FAIL';
  return {
    id: 'generatorCompleted',
    label: 'Generator completed',
    status,
    detail: status === 'PASS' ? `Generated by ${asset.generatorVersion}.` : 'No generator version recorded on this asset.',
  };
}

function checkSvgExists(asset: PortfolioAsset): ReadinessCheck {
  const has = asset.sourceFileReferences.some((f) => f.role === 'svg');
  return { id: 'svgExists', label: 'SVG exists', status: has ? 'PASS' : 'FAIL', detail: has ? 'SVG source file present.' : 'No SVG source file on this asset.' };
}

function checkEpsExists(asset: PortfolioAsset): ReadinessCheck {
  const has = asset.sourceFileReferences.some((f) => f.role === 'eps');
  return {
    id: 'epsExists',
    label: 'EPS exists',
    status: has ? 'PASS' : 'WARNING',
    detail: has ? 'EPS source file present.' : 'No EPS source file — required by some marketplaces, optional for others.',
  };
}

function checkPreviewExists(asset: PortfolioAsset): ReadinessCheck {
  const has = asset.previewReference !== null;
  return { id: 'previewExists', label: 'Preview exists', status: has ? 'PASS' : 'FAIL', detail: has ? 'Preview file present.' : 'No preview file on this asset.' };
}

function checkMetadataExists(asset: PortfolioAsset): ReadinessCheck {
  if (asset.metadataReference !== null) {
    return { id: 'metadataExists', label: 'Metadata exists', status: 'PASS', detail: 'Source metadata JSON present.' };
  }
  const hasSomeDescriptiveFields = asset.styleDna !== null || asset.presetId !== null || asset.compositionType !== null || asset.patternType !== null;
  return {
    id: 'metadataExists',
    label: 'Metadata exists',
    status: hasSomeDescriptiveFields ? 'WARNING' : 'FAIL',
    detail: hasSomeDescriptiveFields
      ? 'No source metadata JSON, but some descriptive fields (style/preset/composition/pattern type) are recorded.'
      : 'No source metadata JSON and no descriptive fields recorded.',
  };
}

function checkSeoExists(submissionsForAsset: SubmissionRecord[]): ReadinessCheck {
  if (submissionsForAsset.length === 0) {
    return { id: 'seoExists', label: 'SEO exists', status: 'FAIL', detail: 'No submission record for this asset — no title/keywords have been written yet.' };
  }
  const best = submissionsForAsset.find((s) => s.titleSnapshot.trim().length > 0 && s.keywordSnapshot.length > 0);
  if (best) {
    return { id: 'seoExists', label: 'SEO exists', status: 'PASS', detail: `Title and ${best.keywordSnapshot.length} keyword(s) recorded on submission ${best.submissionId}.` };
  }
  return { id: 'seoExists', label: 'SEO exists', status: 'WARNING', detail: 'A submission exists but its title or keywords are incomplete.' };
}

function checkCollectionAssignment(asset: PortfolioAsset): ReadinessCheck {
  const has = asset.collectionIds.length > 0;
  return {
    id: 'collectionAssignment',
    label: 'Collection assignment exists',
    status: has ? 'PASS' : 'FAIL',
    detail: has ? `Assigned to ${asset.collectionIds.length} collection(s).` : 'Not assigned to any collection.',
  };
}

function checkMarketplacePackage(asset: PortfolioAsset): ReadinessCheck {
  const hasSvg = asset.sourceFileReferences.some((f) => f.role === 'svg');
  const hasEps = asset.sourceFileReferences.some((f) => f.role === 'eps');
  let anyFileMatch = false;
  let verifiedMatch = false;
  let unverifiedLabel: string | null = null;
  for (const profile of MARKETPLACE_LIST) {
    const fileOk = profile.filenameRules.extension === 'eps' ? hasEps : hasSvg;
    if (!fileOk) continue;
    anyFileMatch = true;
    if (profile.contributorUrlVerified && !profile.future) {
      verifiedMatch = true;
    } else {
      unverifiedLabel = unverifiedLabel ?? profile.label;
    }
  }
  if (verifiedMatch) {
    return { id: 'marketplacePackage', label: 'Marketplace package exists', status: 'PASS', detail: 'File requirements met for at least one verified marketplace profile.' };
  }
  if (anyFileMatch) {
    return {
      id: 'marketplacePackage',
      label: 'Marketplace package exists',
      status: 'WARNING',
      detail: `Needs verification — file requirements met for ${unverifiedLabel ?? 'a marketplace'}, but that marketplace profile isn't yet verified.`,
    };
  }
  return { id: 'marketplacePackage', label: 'Marketplace package exists', status: 'FAIL', detail: 'No marketplace profile\'s required file type is present on this asset.' };
}

function checkQaPassed(snapshot: QualitySnapshot | null): ReadinessCheck {
  if (!snapshot) return { id: 'qaPassed', label: 'QA passed', status: 'FAIL', detail: 'Never evaluated by the quality classifier.' };
  if (snapshot.decision === 'READY') return { id: 'qaPassed', label: 'QA passed', status: 'PASS', detail: 'Quality classifier decision: READY.' };
  if (snapshot.decision === 'REVIEW') return { id: 'qaPassed', label: 'QA passed', status: 'WARNING', detail: 'Quality classifier decision: REVIEW.' };
  return { id: 'qaPassed', label: 'QA passed', status: 'FAIL', detail: 'Quality classifier decision: REJECT.' };
}

function checkCommercialScoreAvailable(snapshot: QualitySnapshot | null): ReadinessCheck {
  const has = snapshot !== null;
  return {
    id: 'commercialScoreAvailable',
    label: 'Commercial score available',
    status: has ? 'PASS' : 'FAIL',
    detail: has ? `Commercial score: ${snapshot!.commercialScore}.` : 'No quality snapshot — commercial score not computed.',
  };
}

function checkBeautyScoreAvailable(snapshot: QualitySnapshot | null): ReadinessCheck {
  const has = snapshot !== null;
  return {
    id: 'beautyScoreAvailable',
    label: 'Beauty score available',
    status: has ? 'PASS' : 'FAIL',
    detail: has ? `Beauty score: ${snapshot!.beautyScore}.` : 'No quality snapshot — beauty score not computed.',
  };
}

function checkDuplicateComplete(asset: PortfolioAsset, siblingAssets: PortfolioAsset[]): ReadinessCheck {
  if (asset.productionAssetId === null) {
    return { id: 'duplicateCheckComplete', label: 'Duplicate check complete', status: 'WARNING', detail: 'No production fingerprint computed for this asset — uniqueness cannot be confirmed.' };
  }
  const duplicate = siblingAssets.find((s) => s.productionAssetId === asset.productionAssetId);
  if (duplicate) {
    return { id: 'duplicateCheckComplete', label: 'Duplicate check complete', status: 'FAIL', detail: `Shares its production fingerprint with "${duplicate.displayName}".` };
  }
  return { id: 'duplicateCheckComplete', label: 'Duplicate check complete', status: 'PASS', detail: 'Production fingerprint is unique across the loaded portfolio.' };
}

function checkRepairHistory(snapshot: QualitySnapshot | null): ReadinessCheck {
  if (!snapshot) return { id: 'repairHistoryComplete', label: 'Repair history complete', status: 'FAIL', detail: 'No quality snapshot — repair status unknown.' };
  if (snapshot.fragmented || snapshot.deadSpace) {
    return {
      id: 'repairHistoryComplete',
      label: 'Repair history complete',
      status: 'WARNING',
      detail: `Latest snapshot still flags ${[snapshot.fragmented ? 'fragmentation' : null, snapshot.deadSpace ? 'dead space' : null].filter(Boolean).join(' and ')}.`,
    };
  }
  return { id: 'repairHistoryComplete', label: 'Repair history complete', status: 'PASS', detail: 'No unresolved fragmentation or dead-space flags.' };
}

function checkExportValidation(asset: PortfolioAsset, snapshot: QualitySnapshot | null): ReadinessCheck {
  const validatedWorkflow = asset.workflowStatus === 'READY_TO_UPLOAD' || asset.workflowStatus === 'SUBMITTED' || asset.workflowStatus === 'APPROVED';
  const hasSvg = asset.sourceFileReferences.some((f) => f.role === 'svg');
  if (validatedWorkflow || (hasSvg && snapshot?.decision === 'READY')) {
    return { id: 'exportValidationComplete', label: 'Export validation complete', status: 'PASS', detail: 'Export files exist and QA has reached a READY decision.' };
  }
  return { id: 'exportValidationComplete', label: 'Export validation complete', status: 'WARNING', detail: 'Not yet validated through an export-ready workflow step.' };
}

const CREDIT: Record<ReadinessCheck['status'], number> = { PASS: 1, WARNING: 0.5, FAIL: 0 };

function computeScore(checks: ReadinessCheck[]): number {
  const byCategory = new Map<ReadinessCategory, ReadinessCheck[]>();
  for (const check of checks) {
    const category = CHECK_CATEGORY[check.id];
    const list = byCategory.get(category) ?? [];
    list.push(check);
    byCategory.set(category, list);
  }
  let total = 0;
  for (const [category, weight] of Object.entries(READINESS_CATEGORY_WEIGHTS) as [ReadinessCategory, number][]) {
    const categoryChecks = byCategory.get(category) ?? [];
    if (categoryChecks.length === 0) continue;
    const avgCredit = categoryChecks.reduce((sum, c) => sum + CREDIT[c.status], 0) / categoryChecks.length;
    total += avgCredit * weight;
  }
  return Math.round(total);
}

function computeBand(score: number, checks: ReadinessCheck[]): CommercialReadinessBand {
  const hasFundamentalBlocker = checks.some((c) => FUNDAMENTAL_BLOCKERS.includes(c.id) && c.status === 'FAIL');
  if (hasFundamentalBlocker) return 'BLOCKED';
  if (score >= DEFAULT_READINESS_THRESHOLD) return 'READY';
  return 'NEEDS_WORK';
}

export function computeCommercialReadiness(input: ReadinessEngineInput): CommercialReadinessReport {
  const { asset, qualitySnapshot, submissionsForAsset, siblingAssets, now } = input;
  const checks: ReadinessCheck[] = [
    checkGeneratorCompleted(asset),
    checkSvgExists(asset),
    checkEpsExists(asset),
    checkPreviewExists(asset),
    checkMetadataExists(asset),
    checkSeoExists(submissionsForAsset),
    checkCollectionAssignment(asset),
    checkMarketplacePackage(asset),
    checkQaPassed(qualitySnapshot),
    checkCommercialScoreAvailable(qualitySnapshot),
    checkBeautyScoreAvailable(qualitySnapshot),
    checkDuplicateComplete(asset, siblingAssets),
    checkRepairHistory(qualitySnapshot),
    checkExportValidation(asset, qualitySnapshot),
  ];
  const score = computeScore(checks);
  return {
    assetId: asset.assetId,
    computedAt: now ?? Date.now(),
    checks,
    score,
    band: computeBand(score, checks),
    failingChecks: checks.filter((c) => c.status === 'FAIL').map((c) => c.id),
    warningChecks: checks.filter((c) => c.status === 'WARNING').map((c) => c.id),
  };
}
