// A small curated library of best-selling stock-pattern niches per style
// family, used as instant local inspiration chips — a lightweight
// complement to the manual ChatGPT/Claude prompt workflow, with no API
// key or network call required.
export const IDEAS = {
  botanical: [
    { title: 'Wild Meadow Botanical', concept: 'loose wildflower meadow with daisies, cosmos and airy stems', palette: 'Pastel Garden' },
    { title: 'Eucalyptus Editorial Bouquet', concept: 'large layered eucalyptus and rose bouquets on cream ground', palette: 'Cream Coral Garden' },
    { title: 'Scandinavian Sage Botanical', concept: 'minimal olive branches and sage leaves, calm negative space', palette: 'Scandinavian Sage' },
    { title: 'Vintage Cottage Garden', concept: 'ditsy tulips and daisies scattered densely, nostalgic', palette: 'Vintage Cream' },
    { title: 'Luxury Dark Botanical Wallpaper', concept: 'dramatic peonies and berries on a deep emerald ground', palette: 'Luxury Dark' },
    { title: 'Coastal Coral Florals', concept: 'coral-toned roses with soft foliage, breezy layout', palette: 'Cream Coral Garden' },
    { title: 'Fern & Willow Woodland', concept: 'fern fronds and willow branches, muted forest palette', palette: 'Neutral Textile' },
    { title: 'Blush Cosmos Bouquet', concept: 'blush cosmos and tulips in a diagonal drift', palette: 'Pastel Garden' },
    { title: 'Cottagecore Ditsy Daisy', concept: 'tiny daisies and buds in a dense half-drop repeat', palette: 'Vintage Cream' },
    { title: 'Botanical Line Study', concept: 'sparse editorial botanical with lots of negative space', palette: 'Neutral Textile' },
  ],
  geometric: [
    { title: 'Mid Century Sunburst', concept: 'retro sunburst medallions with arches, warm palette', palette: 'Mid Century Bold' },
    { title: 'Bauhaus Terrazzo Grid', concept: 'terrazzo clusters and half moons on a balanced grid', palette: 'Cool Minimal' },
    { title: 'Terrazzo Confetti', concept: 'terrazzo clusters with scattered confetti dashes', palette: 'Cool Minimal' },
    { title: 'Soft Arch Wallpaper', concept: 'stacked soft arches, minimal two-tone', palette: 'Mid Century Bold' },
    { title: 'Retro Wave Bands', concept: 'ribbon waves and triangles in a diagonal drift', palette: 'Muted Terracotta' },
    { title: 'Modern Dot Grid Texture', concept: 'small dot clusters as a coordinate blender texture', palette: 'Cool Minimal' },
    { title: 'Abstract Pebble Path', concept: 'organic pebble shapes scattered airy', palette: 'Neutral Textile' },
    { title: 'Art Deco Sunrise', concept: 'sunburst hero motifs with geometric fan accents', palette: 'Mid Century Bold' },
    { title: 'Memphis Confetti Pop', concept: 'bold terrazzo shapes and confetti dashes, playful bright', palette: 'Soft Pastel' },
    { title: 'Minimal Triangle Rhythm', concept: 'soft triangles in a half-drop brick layout', palette: 'Cool Minimal' },
  ],
  textile: [
    { title: 'Ikat Diamond Weave', concept: 'ikat diamonds and chevrons, ethnic woven texture', palette: 'Muted Terracotta' },
    { title: 'Block Print Medallion', concept: 'hand block-print style medallions, warm earthy tone', palette: 'Vintage Cream' },
    { title: 'Boho Chevron Textile', concept: 'chevron rows with woven dash filler', palette: 'Muted Terracotta' },
    { title: 'Folk Stamp Repeat', concept: 'block stamp motifs in a grid balanced repeat', palette: 'Neutral Textile' },
    { title: 'Woven Stripe Ditsy', concept: 'stripe bands with tiny cross fillers, calm linen feel', palette: 'Cool Minimal' },
    { title: 'Ethnic Medallion Wallpaper', concept: 'large ikat medallions, deep saturated palette', palette: 'Mid Century Bold' },
    { title: 'Rustic Loom Texture', concept: 'woven dash blender texture for coordinates', palette: 'Neutral Textile' },
    { title: 'Global Textile Diamond', concept: 'diamond and cross motifs, worldly boho', palette: 'Muted Terracotta' },
    { title: 'Handmade Fabric Ditsy', concept: 'tiny cross and thread dot ditsy repeat', palette: 'Vintage Cream' },
    { title: 'Heritage Block Print', concept: 'stamped block motifs on a half-drop brick', palette: 'Mid Century Bold' },
  ],
  seasonal: [
    { title: 'Cozy Christmas Botanical', concept: 'gift boxes, snowflakes and festive ornaments', palette: 'Luxury Dark' },
    { title: 'Cute Halloween Pumpkin Patch', concept: 'pumpkins and stars on a playful scatter', palette: 'Mid Century Bold' },
    { title: 'Spring Bunny Garden', concept: 'bunnies, hearts and leaves for Easter', palette: 'Pastel Garden' },
    { title: 'Winter Snowflake Wonderland', concept: 'snowflakes and stars, cool winter palette', palette: 'Cool Minimal' },
    { title: 'Autumn Harvest Leaves', concept: 'falling leaves and pumpkins, warm harvest tone', palette: 'Muted Terracotta' },
    { title: 'Valentine Heart Bloom', concept: 'hearts and stars in a dense ditsy repeat', palette: 'Soft Pastel' },
    { title: 'Festive Holiday Ornaments', concept: 'gift box and ornament icons, celebratory', palette: 'Luxury Dark' },
    { title: 'Easter Bunny Meadow', concept: 'bunnies, leaves and hearts for spring stock', palette: 'Pastel Garden' },
    { title: 'New Year Celebration Sparkle', concept: 'stars and ornaments, celebratory sparkle', palette: 'Mid Century Bold' },
    { title: 'Cozy Winter Cabin', concept: 'snowflakes and clouds, soft muted winter', palette: 'Neutral Textile' },
  ],
  commercial: [
    { title: 'Coffee Shop Icon Set', concept: 'coffee cups and hearts, cozy kitchen pattern', palette: 'Vintage Cream' },
    { title: 'Pet Lover Paw Print', concept: 'paw prints and hearts, playful pet pattern', palette: 'Soft Pastel' },
    { title: 'Bakery Sweet Treats', concept: 'cakes and hearts, bakery packaging pattern', palette: 'Soft Pastel' },
    { title: 'Cloud Nine Nursery', concept: 'clouds and stars, gentle nursery pattern', palette: 'Pastel Garden' },
    { title: 'Wellness Self Care Icons', concept: 'hearts, stars and clouds, calming wellness set', palette: 'Cool Minimal' },
    { title: 'Kitchen Comfort Pattern', concept: 'coffee cups and cakes, warm kitchen textile', palette: 'Muted Terracotta' },
    { title: 'Planner Sticker Set', concept: 'stars, hearts and cups for planner stickers', palette: 'Soft Pastel' },
    { title: 'Cute Pet Cafe Mashup', concept: 'paw prints and coffee cups combined', palette: 'Vintage Cream' },
    { title: 'Baby Shower Cloud Pattern', concept: 'clouds and stars, soft pastel baby pattern', palette: 'Pastel Garden' },
    { title: 'Feel Good Icon Blender', concept: 'mixed hearts, stars and clouds as a blender texture', palette: 'Cool Minimal' },
  ],
};
