import type { DesignEvaluation } from './designEvaluation';
import type { CommercialReadinessReport } from '../commercial/domain/types';
import type { VisualIssueId } from '../critic/visualAnalysis';

// Design Refinement Studio Pro, Mission 2 — AI Design Coach. Not a new AI
// engine: every advice item here is a deterministic text template keyed
// off an id that `critic/problems.ts`'s `detectProblems` or
// `critic/visualAnalysis.ts`'s `detectVisualIssues` already detected as
// real (both already reused as-is by `design/designEvaluation.ts`), or off
// a FAIL/WARNING check `commercial/readinessEngine.ts` already computed.
// This module invents no score, no probability, no judgment beyond
// pointing at the one already-editable `GenerateParams` control
// (`components/designEdit/DesignEditControls.tsx`) most directly tied to
// each real, already-detected condition.

export type DesignCoachSource = 'problem' | 'issue' | 'readiness';
export type DesignCoachSeverity = 'high' | 'medium' | 'low';

export interface DesignCoachAdvice {
  id: string;
  source: DesignCoachSource;
  severity: DesignCoachSeverity;
  message: string;
  suggestion: string;
}

const PROBLEM_SUGGESTIONS: Record<string, string> = {
  quadrantImbalance: 'Try lowering Motif Density slightly, or switch Layout to spread motifs more evenly across the tile.',
  largeEmptyHole: 'Increase Motif Density or reduce Negative Space to fill the empty region.',
  heroClustering: 'Increase Rotation Jitter or Scale Jitter, or pick a Hierarchy preset with more hero separation.',
  adjacentRepetition: 'Increase Rotation Jitter and Scale Jitter for more instance-to-instance variety.',
  edgeImbalance: 'Try a different Layout, or adjust Pattern Scale.',
  lowPaletteContrast: 'Switch Palette or increase Color Count.',
  cornerDeadZone: 'Reduce Negative Space, or try a different Layout — this affects how corners look when the tile repeats.',
  repetitiveMotifShapes: 'Increase Color Count, or try a different Category for more shape variety.',
  zeroMotifOverlap: 'Increase Overlap so motifs read as a composed pattern instead of isolated stickers.',
  heroInsufficientDetail: 'Pick a Hierarchy preset with a larger hero scale.',
  equalSpacingDetected: 'Increase Rotation Jitter and Scale Jitter, or switch to a more organic Layout.',
  tooManyIsolatedObjects: 'Increase Motif Density or Overlap so fewer motifs sit isolated.',
  weakHierarchy: 'Pick a stronger Hierarchy preset (e.g. Hero Focus) so hero/secondary/filler/accent tiers read clearly.',
  lowClusterCohesion: 'Increase Motif Density, or pick a Hierarchy preset with more secondary support around each hero.',
  repeatedMotifOrientation: 'Increase Rotation Jitter.',
  gridAppearance: 'Increase Rotation Jitter — or this may be expected if you intend a Grid/Lattice Layout.',
  monotonousScale: 'Increase Scale Jitter.',
  mechanicalComposition: 'Increase Rotation Jitter and Scale Jitter together, or switch to a more organic Layout.',
};

const ISSUE_SUGGESTIONS: Record<VisualIssueId, string> = {
  weakHero: 'Pick a Hierarchy preset with a larger hero scale, or increase Color Count for more contrast.',
  crowdedAreas: 'Reduce Motif Density or increase Negative Space.',
  deadSpace: 'Increase Motif Density or reduce Negative Space.',
  mechanicalSpacing: 'Increase Rotation Jitter and Scale Jitter.',
  gridAppearance: 'Increase Rotation Jitter — or this may be expected if you intend a Grid/Lattice Layout.',
  weakClusters: 'Increase Motif Density, or pick a Hierarchy preset with more secondary support.',
  lowDetail: 'Increase Color Count or Motif Density.',
  repeatedRotation: 'Increase Rotation Jitter.',
  repeatedScale: 'Increase Scale Jitter.',
  weakFlow: 'Try a different Layout, or adjust Overlap.',
  fragmentedSilhouette: 'Increase Motif Density or Overlap to connect motifs into one coherent silhouette.',
  lowHeroVisibility: 'Pick a Hierarchy preset with a larger hero scale.',
  weakHierarchy: 'Pick a stronger Hierarchy preset so role tiers are visually distinct.',
  tooManyFillers: 'Pick a Hierarchy preset with a lower filler ratio.',
};

const SEVERITY_RANK: Record<DesignCoachSeverity, number> = { high: 3, medium: 2, low: 1 };

/** Human-readable, deterministic advice for the current live edit, built
 * only from data `evaluateDesign` and (optionally) the original asset's
 * already-persisted Commercial Readiness already computed for real —
 * nothing here is generated by a model or fabricated. */
export function buildDesignCoachAdvice(evaluation: DesignEvaluation, originalReadiness: CommercialReadinessReport | null = null): DesignCoachAdvice[] {
  const advice: DesignCoachAdvice[] = [];

  for (const problem of evaluation.problems) {
    const suggestion = PROBLEM_SUGGESTIONS[problem.id];
    if (!suggestion) continue;
    advice.push({ id: `problem:${problem.id}`, source: 'problem', severity: problem.severity, message: problem.label, suggestion });
  }

  for (const issue of evaluation.issues) {
    if (!issue.detected) continue;
    const suggestion = ISSUE_SUGGESTIONS[issue.id];
    if (!suggestion) continue;
    advice.push({ id: `issue:${issue.id}`, source: 'issue', severity: 'medium', message: `${issue.label} — ${issue.evidence}`, suggestion });
  }

  if (originalReadiness) {
    for (const check of originalReadiness.checks) {
      if (check.status === 'PASS') continue;
      advice.push({
        id: `readiness:${check.id}`,
        source: 'readiness',
        severity: check.status === 'FAIL' ? 'high' : 'medium',
        message: `${check.label}: ${check.detail}`,
        suggestion: 'This is tracked outside the pattern shape (collection/SEO/export workflow) — resolve it from Portfolio Manager after approving this version.',
      });
    }
  }

  return advice.sort((a, b) => SEVERITY_RANK[b.severity] - SEVERITY_RANK[a.severity]);
}
